- css/default.css
- index.html
> Footer innehåll

- main.html
> lagt till mina filer

- service.html
Lagt till default html från index.html
> Lagt till html i service.html

- css/service.css
Kopierad default css till service.css
> Lagt till default css i service.css

- css/about.css
> Css-2-text

- css/about.css
> Css-4-text

- service.html
Skapade en container runt body.
> Skapade en conatiner runt body

- service.html
Skapade klasserna:
box-section-1
box-section-2
> Skapade klasserna

- service.html
La till title och text till box-section-1 och box-section-2.
> La till title och text till box-section-1 och box-section-2

- service.html
Skapade sektioner för footer. 
- Title och text. 
- Prenumerera-knapp.
- Lista för socialmedier.
> La till sektioner i footer

- service.html
Skapade sektioner för bakgrundsbilder i box-section-1 och box-section-2.
> La till sektioner för bakgrundsbilder

- css/service.css
La till css för klassen content.
> La till css för content

- css/service.css
La till css för header och nav.
> La till css för header och nav

- css/service.css
La till css för box-section-1 och box-section-2, och css för alla individuella boxar.
> La till css för box-section-1 och 2.

- css/service.css
> La till footer till css

- css/service.css
> La till en knapp till footer

- service.html
> Tog bort footer links

- css/service.css
> Tog bort footer ul från css

- css/service.css
La till margin-top och margin-bottom på footer-knappen.
> Lag till margin top och bottom på footer-knappen

- service.html
Länkade bilder till service.html
> Länkade bilder till service.html

- css/default.css
- index.html
La till footer i index.html och default.css
> La till footer till index och css

- css/service.css
> La till media queries

- css/service.css
> La till css för bilderna

- service.html
> La till googlefonts

- service.html
La till ny text till mina boxar
> La till ny text till mina boxar

- service.html
> Fixade google fonts länk

- css/service.css
> Fixade google fonts css
